
name: tm-text-tagging-ui-workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup NPM
        uses: actions/setup-node@v2.4.1
        with:
          check-latest: true
          node-version: '16.x'

      - name: Java Version
        run: echo $JAVA_HOME

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/tailoredmediaproject/tm-text-tagging-ui:latest