
name: tm-text-tagging-ui-workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Setup NPM
        uses: actions/setup-node@v2.4.1
        with:
          check-latest: true
          node-version: '12.x'

      - name: Java Version
        run: echo $JAVA_HOME

      - name: Java Check
        run: ls -R /usr/lib/jvm/

      - name: Change JAVA_HOME
        run: |
          export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/tailoredmediaproject/tm-text-tagging-ui:latest