
name: tm-text-tagging-ui-workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'

      - name: Setup NPM
        uses: actions/setup-node@v2.4.1
        with:
          check-latest: true
          node-version: '12.x'

      - name: Install and run Docker
        run: |
          brew install --cask docker virtualbox
          brew install docker-machine
          docker-machine create --driver virtualbox default
          docker-machine restart
          eval "$(docker-machine env default)"
          docker-machine regenerate-certs default
          docker-machine restart

      - name: Java Version
        run: java --version && javac --version

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/tailoredmediaproject/tm-text-tagging-ui:latest